[package]
name = "imageflow_abi"
version = "0.1.0"
authors = ["Nathanael Jones <nathanael.jones@gmail.com>"]
workspace = "../"
build = "build.rs"

[lib]
name = "imageflow"
doc = true
crate-type = ["cdylib"]
doctest = false

[dependencies]
libc = "0.2"
imageflow_core = { path = "../imageflow_core", version = "*" }
backtrace = "*"
smallvec="*"

[build-dependencies]
imageflow_helpers = { path = "../imageflow_helpers", version = "*" }
moz-cheddar = "0.4.1"
regex = "*"
