[package]
name = "imageflow_helpers"
version = "0.1.0"
authors = ["Nathanael Jones <nathanael.jones@gmail.com>"]
workspace = "../"

[dependencies]
regex = "*"
hyper = "*"
blake2-rfc = "*"
lazy_static = "*"
bit-vec = "*"
twox-hash = "1.0.0"
fnv = "*"
chrono =  "0.2"
os_type = "0.5.0"
zip = { version = "0.2", default-features = false }
serde = "*"
serde_json = "*"
libc = "*"

[profile.release]
debug = true