[package]
name = "imageflow_server"
version = "0.1.0"
authors = ["Nathanael Jones <nathanael.jones@gmail.com>"]
workspace = "../"



[dependencies]
libc = "0.2.0"
clap = "2"
router = "*"
iron = "*"


time = "*"
hyper = "*"
rustc-serialize = "*"
threadpool = "1.0"
serde = "*"
serde_json = "*"
imageflow_core = { path = "../imageflow_core", version = "*" }
imageflow_types = { path = "../imageflow_types", version = "*" }
imageflow_helpers = { path = "../imageflow_helpers", version = "*" }
imageflow_riapi = { path = "../imageflow_riapi", version = "*" }
# imageflow_tool = { path = "../imageflow_tool", version = "*" }
blake2-rfc = "0.2.17"
rand = "*"
lru-cache = "*"
persistent = "*"
regex = "*"
lazy_static ="*"
log="*"
env_logger="*"
wait-timeout = "0.1"

[build-dependencies]
cmake = "0.1.17"


[profile.release]
debug = true


[[bin]]
name = "imageflow_server"
path = "src/main.rs"
doc = false

[dependencies.logger]

git = "https://github.com/iron/logger.git"
